### ISSUE TITLE
Left or right side of SHA256 for KID ?

### ISSUE THREAD

**Issue by dirkx** [ehn-digital-green-development/hcert-spec#5]
Should we use the term left or right perhaps? Pros and cons for the choice between left and right:

* Left: Have been the de-facto way to do it in the internet-standards world ever since RFC 2104 (1997) I believe?
* Right: Some C# library apparently wraps hashes into an ASN.1 structure which adds data on the left of the hash?

**Comment by jschlyter** [comment]
As discussed before, I strongly suggest we use the leftmost just as any other truncated hash. Adjusting to implementation issues in some language just because they mix ASN.1 encoded data with raw content is the wrong way to go IMHO.

**Comment by jschlyter** [comment]
One should also note that the kid encoding is only important when constructing the trusted list (TL) as long as the TL includes the kid. Validators only needs to match the kid in the hcert aginst the kid on the TL and _does not_ need to know about the wrapping.

Because of this reason I suggest the kid is not not discussed further in the CWT claims section of the draft, but only in "Appendix B". It is not part of the hcert encoding scheme at all, it is a pure key conversion function. The [trusted list for my hcert testdata](https://github.com/ehn-digital-green-development/hcert-testdata/blob/main/testdata/jwks.json) explicitly lists the kid for this reason.

**Comment by dirkx** [comment]
Will make the latter change.

**Comment by jschlyter** [comment]
> Will make the latter change.

Good, but I also believe we should still use the first 8 bytes for standard truncated hash reasons. There are no (to me) known truncation schemes for hashes that does otherwise.

**Comment by jschlyter** [comment]
Proposed text below. Perhaps @Razumain can provide a good normative reference to how the fingerprint is calculated; it's a plain hash over the certificate in DER format, but a reference to a RFC would be useful.

### The Key Identifier (KIDs)

The key identifier (kid) is calculated when constructing the list of trusted list of public keys from DSC certificates, and consists of a truncated (first 8 bytes) SHA-256 fingerprint of the DSC.

Note: Verifiers does not need to calculate the kid based on the DSC certificate and can directly match the key identifier in issued health certificate with the kid on the trusted list.
